### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by RDSJC** [Autokaka/refined_c_compiler#1]
You've really done an awesome work!  I do a black box test in a incremental way, and it seems that there is something wrong with if and while statement. The screenshots are as below. 
![1](https://user-images.githubusercontent.com/8330000/83771413-d53b9f80-a6b4-11ea-908f-5cbc7a540bf8.png)
![2](https://user-images.githubusercontent.com/8330000/83771422-d967bd00-a6b4-11ea-81d4-6e6cc62258a7.png)
![3](https://user-images.githubusercontent.com/8330000/83771431-dbca1700-a6b4-11ea-9959-952074d50a5b.png)
![4](https://user-images.githubusercontent.com/8330000/83771434-dd93da80-a6b4-11ea-9b4f-d3310da50181.png)

**Comment by wangty225** [comment]
**+1**

**Comment by Autokaka** [comment]
Hello, thanks for your issue. Please notice that the grammar (修改的LL(1)文法.md) and guidebook (编译原理上机实验指导书.md) given in doc directory does not fit **that c language** grammar. The "c" in refined_c_compiler has other meanings. It's just a new language named "c", not a subset of c/c++. Sorry for the wrong introduction in README.md. I will make a revise for the documents right now. 
I used to have the same question before, after communicating, however, according to the explanation of teacher LiuWangshu, the correct use of while statement should be like this:
```c
main() {
  int a, b;
  a = 1;
  b = 2;

  while(a > 0) 
  do { // "do" must be declared here.
    a = a + b * a;
  }
}
```
You can also refer to the grammar in `文法.md` where loop sentences is defined in this way:
![image](https://user-images.githubusercontent.com/20894949/83839985-01e0cd00-a730-11ea-88cf-9aaa2c803bed.png)
As you can see, there is a `DoStatement` in the grammar. So in order to successfullt declare a loop statement, please use the grammar in code block above.

As for condition sentences, the explanation is the same. In grammar, condition sentence is defined in this way: 
![image](https://user-images.githubusercontent.com/20894949/83840483-44ef7000-a731-11ea-9789-8fff33f10477.png)
Because of that, the correct usage of condition sentences must be like this: 
```c
main() {
  int a, b;
  a = 1;
  b = 2;

  if (a > 0) {
    a = a + b * a;
  } else {} // must have an "else" statement
}
```
Thanks for you report. This project strictly observe the rules in duidebook(编译原理上机实验指导书.md), I just make the grammar more rigorous without modifying other parts. For more instructions, please follow the guidebook.

**Comment by Autokaka** [comment]
The tested results after following the grammar are provided below:
![image](https://user-images.githubusercontent.com/20894949/83841103-b845b180-a732-11ea-9915-28612e76e031.png)
![image](https://user-images.githubusercontent.com/20894949/83841128-cd224500-a732-11ea-8b89-d075a38168a2.png)
